#!/usr/bin/env python3
"""
Komoot Ascent Tracker - Scraper
Fetches all recorded activities for a Komoot user and saves them as a JavaScript data file.

Usage:
    python scraper.py

Cron job (daily at 8am):
    0 8 * * * cd /Users/pierre/Code/Perso/Ascent && python3 scraper.py >> scraper.log 2>&1
"""

import requests
import json
import os
from datetime import datetime

USER_ID = "1939029710958"
PAGE_SIZE = 100


def seconds_to_hm(seconds):
    h = int(seconds) // 3600
    m = (int(seconds) % 3600) // 60
    return h, m


def fetch_all_tours():
    """Fetch all public recorded tours from Komoot API with pagination."""
    all_tours = []
    page = 0

    while True:
        url = (
            f"https://api.komoot.de/v007/users/{USER_ID}/tours/"
            f"?type=tour_recorded&sort_field=date&sort_direction=desc"
            f"&status=public&page_size={PAGE_SIZE}&page={page}"
        )
        headers = {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
        }

        try:
            response = requests.get(url, headers=headers, timeout=30)
            response.raise_for_status()
            data = response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error fetching page {page}: {e}")
            break

        tours = data.get("_embedded", {}).get("tours", [])
        if not tours:
            break

        all_tours.extend(tours)
        print(f"  Page {page}: fetched {len(tours)} tours (total: {len(all_tours)})")

        # Pagination: check if there are more pages
        total_elements = data.get("page", {}).get("totalElements", 0)
        if total_elements and len(all_tours) >= total_elements:
            break
        if len(tours) < PAGE_SIZE:
            break

        page += 1

    return all_tours


def process_tour(tour):
    """Extract and compute the key metrics from a raw tour object."""
    duration = tour.get("duration", 0)
    time_in_motion = tour.get("time_in_motion", duration) or duration
    distance_m = tour.get("distance", 0)
    elevation_up = tour.get("elevation_up", 0)
    elevation_down = tour.get("elevation_down", 0)

    # Speed is calculated from moving time (more accurate than total duration)
    speed = (distance_m / time_in_motion * 3.6) if time_in_motion > 0 else 0
    h, m = seconds_to_hm(duration)

    return {
        "id": tour["id"],
        "name": tour.get("name", ""),
        "date": tour["date"],
        "sport": tour.get("sport", ""),
        # Display values
        "duration_s": int(duration),
        "time_h": h,
        "time_m": m,
        "distance_km": round(distance_m / 1000, 1),
        "speed_kmh": round(speed, 1),
        "ascent_m": round(elevation_up),
        "descent_m": round(elevation_down),
    }


def main():
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Fetching tours from Komoot API...")

    raw_tours = fetch_all_tours()
    print(f"Total tours fetched: {len(raw_tours)}")

    processed = [process_tour(t) for t in raw_tours]

    total_ascent = sum(t["ascent_m"] for t in processed)
    total_distance = sum(t["distance_km"] for t in processed)

    print(f"Total ascent: {total_ascent:,}m")
    print(f"Total distance: {total_distance:,.1f}km")

    output = {
        "user_id": USER_ID,
        "display_name": "Charles GOEMANS",
        "fetched_at": datetime.now().isoformat(),
        "tours": processed,
    }

    os.makedirs("data", exist_ok=True)

    # Write as JS global variable (loaded directly by index.html)
    js_content = "// Auto-generated by scraper.py — DO NOT EDIT MANUALLY\n"
    js_content += f"const KOMOOT_DATA = {json.dumps(output, indent=2, ensure_ascii=False)};\n"

    with open("data/tours.js", "w", encoding="utf-8") as f:
        f.write(js_content)

    # Also save raw JSON for other uses
    with open("data/tours.json", "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"Data saved to data/tours.js and data/tours.json")
    print(f"Done! Open index.html to view the visualization.")


if __name__ == "__main__":
    main()
